### ISSUE TITLE
请问页面宽度怎么调整？

### ISSUE THREAD

**Issue by caecfd** [xb2016/Kratos#539]
自定义css似乎不起作用

**Comment by n0099** [comment]
什么页面的宽度

**Comment by caecfd** [comment]
您好，已收到您的邮件，我会在最短的时间内给您回复，谢谢！

**Comment by caecfd** [comment]
> 什么页面的宽度

就是主页面的宽度。目前在手机上适配非常好，但是在电脑上页面显得太窄了，有些文章标题都没法显示齐全。

**Comment by wkingnet** [comment]
后台外观-自定义-额外CSS里，加一句
```
@media (min-width: 1310px){
.container {
/*max-width: 71.8%;*/
	max-width: 1700px;
}
	.col-lg-4 {
	-ms-flex: 0 0 28%;
	flex: 0 0 28%;
	max-width: 28%
}

.col-lg-8 {
	-ms-flex: 0 0 72%;
	flex: 0 0 72%;
	max-width: 72%
}
}
```

**Comment by n0099** [comment]
也可以写进子主题`style.css`： https://developer.wordpress.org/themes/advanced-topics/child-themes/

**Comment by caecfd** [comment]
您好，已收到您的邮件，我会在最短的时间内给您回复，谢谢！

**Comment by g93920079** [comment]
> 后台外观-自定义-额外CSS里，加一句
> 
> ```
> @media (min-width: 1310px){
> .container {
> 	max-width: 1700px;
> }
> }
> ```

你好，按照上述命令操作后，首页分类、标签聚合那的整个一栏都会拉长，有没有办法只拉长文章列表那一栏（即左侧那一排）？

**Comment by jkoor** [comment]
> > 后台外观-自定义-额外CSS里，加一句
> > ```
> > @media (min-width: 1310px){
> > .container {
> > 	max-width: 1700px;
> > }
> > }
> > ```
> 
> 你好，按照上述命令操作后，首页分类、标签聚合那的整个一栏都会拉长，有没有办法只拉长文章列表那一栏（即左侧那一排）？

在自定义css里再加入以下代码，28%和72%对应的是两栏比例
```css
.col-lg-4 {
	-ms-flex: 0 0 28%;
	flex: 0 0 28%;
	max-width: 28%
}

.col-lg-8 {
	-ms-flex: 0 0 72%;
	flex: 0 0 72%;
	max-width: 72%
}
```
